// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddServiceIdentityReducer from "./add_service_identity_reducer";
import AdminHideReducer from "./admin_hide_reducer";
import AnswerClarificationReducer from "./answer_clarification_reducer";
import CancelQueryReducer from "./cancel_query_reducer";
import ClaimServiceRoleReducer from "./claim_service_role_reducer";
import CreateCommentReducer from "./create_comment_reducer";
import CreatePostReducer from "./create_post_reducer";
import DeactivateDeviceReducer from "./deactivate_device_reducer";
import DeleteCommentReducer from "./delete_comment_reducer";
import DeletePostReducer from "./delete_post_reducer";
import RegisterDeviceReducer from "./register_device_reducer";
import ReportContentReducer from "./report_content_reducer";
import SetNotificationsPausedReducer from "./set_notifications_paused_reducer";
import SetProfileReducer from "./set_profile_reducer";
import SubmitQueryReducer from "./submit_query_reducer";
import SubmitResponseReducer from "./submit_response_reducer";
import UpdateLocationReducer from "./update_location_reducer";
import UpsertPlaceReducer from "./upsert_place_reducer";
import WorkerAddObservationReducer from "./worker_add_observation_reducer";
import WorkerAddQueryEventReducer from "./worker_add_query_event_reducer";
import WorkerAttachQueryReducer from "./worker_attach_query_reducer";
import WorkerCreateJobReducer from "./worker_create_job_reducer";
import WorkerCreatePromptBatchReducer from "./worker_create_prompt_batch_reducer";
import WorkerInvalidateObservationReducer from "./worker_invalidate_observation_reducer";
import WorkerMarkNotifiedReducer from "./worker_mark_notified_reducer";
import WorkerRecordImpactReducer from "./worker_record_impact_reducer";
import WorkerSetAdminReducer from "./worker_set_admin_reducer";
import WorkerSetAnswerReducer from "./worker_set_answer_reducer";
import WorkerSetClarificationReducer from "./worker_set_clarification_reducer";
import WorkerSetJobStatusReducer from "./worker_set_job_status_reducer";
import WorkerSetPostSummaryReducer from "./worker_set_post_summary_reducer";
import WorkerSetQueryPlanReducer from "./worker_set_query_plan_reducer";
import WorkerSetQueryStatusReducer from "./worker_set_query_status_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import MyCommentsRow from "./my_comments_table";
import MyDevicesRow from "./my_devices_table";
import MyImpactRow from "./my_impact_table";
import MyLocationRow from "./my_location_table";
import MyPostsRow from "./my_posts_table";
import MyProfileRow from "./my_profile_table";
import MyPromptsRow from "./my_prompts_table";
import MyQueriesRow from "./my_queries_table";
import MyQueryEventsRow from "./my_query_events_table";
import PlaceRow from "./place_table";
import PulseCommentsRow from "./pulse_comments_table";
import PulsePostsRow from "./pulse_posts_table";
import SvcCommentRow from "./svc_comment_table";
import SvcDeviceRow from "./svc_device_table";
import SvcEvidenceJobRow from "./svc_evidence_job_table";
import SvcImpactEventRow from "./svc_impact_event_table";
import SvcObservationRow from "./svc_observation_table";
import SvcPostRow from "./svc_post_table";
import SvcPromptBatchRow from "./svc_prompt_batch_table";
import SvcPromptRecipientRow from "./svc_prompt_recipient_table";
import SvcPromptResponseRow from "./svc_prompt_response_table";
import SvcQueryRow from "./svc_query_table";
import SvcQueryEventRow from "./svc_query_event_table";
import SvcReportRow from "./svc_report_table";
import SvcUserLocationRow from "./svc_user_location_table";
import SvcUserProfileRow from "./svc_user_profile_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  place: __table({
    name: 'place',
    indexes: [
      { accessor: 'community', name: 'place_community_idx_btree', algorithm: 'btree', columns: [
        'community',
      ] },
      { accessor: 'id', name: 'place_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'place_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlaceRow),
  myComments: __table({
    name: 'my_comments',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCommentsRow),
  myDevices: __table({
    name: 'my_devices',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDevicesRow),
  myImpact: __table({
    name: 'my_impact',
    indexes: [
    ],
    constraints: [
    ],
  }, MyImpactRow),
  myLocation: __table({
    name: 'my_location',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLocationRow),
  myPosts: __table({
    name: 'my_posts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPostsRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  myPrompts: __table({
    name: 'my_prompts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPromptsRow),
  myQueries: __table({
    name: 'my_queries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQueriesRow),
  myQueryEvents: __table({
    name: 'my_query_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyQueryEventsRow),
  pulseComments: __table({
    name: 'pulse_comments',
    indexes: [
    ],
    constraints: [
    ],
  }, PulseCommentsRow),
  pulsePosts: __table({
    name: 'pulse_posts',
    indexes: [
    ],
    constraints: [
    ],
  }, PulsePostsRow),
  svcComment: __table({
    name: 'svc_comment',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcCommentRow),
  svcDevice: __table({
    name: 'svc_device',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcDeviceRow),
  svcEvidenceJob: __table({
    name: 'svc_evidence_job',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcEvidenceJobRow),
  svcImpactEvent: __table({
    name: 'svc_impact_event',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcImpactEventRow),
  svcObservation: __table({
    name: 'svc_observation',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcObservationRow),
  svcPost: __table({
    name: 'svc_post',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcPostRow),
  svcPromptBatch: __table({
    name: 'svc_prompt_batch',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcPromptBatchRow),
  svcPromptRecipient: __table({
    name: 'svc_prompt_recipient',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcPromptRecipientRow),
  svcPromptResponse: __table({
    name: 'svc_prompt_response',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcPromptResponseRow),
  svcQuery: __table({
    name: 'svc_query',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcQueryRow),
  svcQueryEvent: __table({
    name: 'svc_query_event',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcQueryEventRow),
  svcReport: __table({
    name: 'svc_report',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcReportRow),
  svcUserLocation: __table({
    name: 'svc_user_location',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcUserLocationRow),
  svcUserProfile: __table({
    name: 'svc_user_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, SvcUserProfileRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_service_identity", AddServiceIdentityReducer),
  __reducerSchema("admin_hide", AdminHideReducer),
  __reducerSchema("answer_clarification", AnswerClarificationReducer),
  __reducerSchema("cancel_query", CancelQueryReducer),
  __reducerSchema("claim_service_role", ClaimServiceRoleReducer),
  __reducerSchema("create_comment", CreateCommentReducer),
  __reducerSchema("create_post", CreatePostReducer),
  __reducerSchema("deactivate_device", DeactivateDeviceReducer),
  __reducerSchema("delete_comment", DeleteCommentReducer),
  __reducerSchema("delete_post", DeletePostReducer),
  __reducerSchema("register_device", RegisterDeviceReducer),
  __reducerSchema("report_content", ReportContentReducer),
  __reducerSchema("set_notifications_paused", SetNotificationsPausedReducer),
  __reducerSchema("set_profile", SetProfileReducer),
  __reducerSchema("submit_query", SubmitQueryReducer),
  __reducerSchema("submit_response", SubmitResponseReducer),
  __reducerSchema("update_location", UpdateLocationReducer),
  __reducerSchema("upsert_place", UpsertPlaceReducer),
  __reducerSchema("worker_add_observation", WorkerAddObservationReducer),
  __reducerSchema("worker_add_query_event", WorkerAddQueryEventReducer),
  __reducerSchema("worker_attach_query", WorkerAttachQueryReducer),
  __reducerSchema("worker_create_job", WorkerCreateJobReducer),
  __reducerSchema("worker_create_prompt_batch", WorkerCreatePromptBatchReducer),
  __reducerSchema("worker_invalidate_observation", WorkerInvalidateObservationReducer),
  __reducerSchema("worker_mark_notified", WorkerMarkNotifiedReducer),
  __reducerSchema("worker_record_impact", WorkerRecordImpactReducer),
  __reducerSchema("worker_set_admin", WorkerSetAdminReducer),
  __reducerSchema("worker_set_answer", WorkerSetAnswerReducer),
  __reducerSchema("worker_set_clarification", WorkerSetClarificationReducer),
  __reducerSchema("worker_set_job_status", WorkerSetJobStatusReducer),
  __reducerSchema("worker_set_post_summary", WorkerSetPostSummaryReducer),
  __reducerSchema("worker_set_query_plan", WorkerSetQueryPlanReducer),
  __reducerSchema("worker_set_query_status", WorkerSetQueryStatusReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `myComments` instead. This alias will be removed in the next major version. */
    readonly "my_comments": Omit<typeof tablesSchema.schemaType.tables["myComments"], "accessorName"> & { readonly accessorName: "my_comments" };
    /** @deprecated Use `myDevices` instead. This alias will be removed in the next major version. */
    readonly "my_devices": Omit<typeof tablesSchema.schemaType.tables["myDevices"], "accessorName"> & { readonly accessorName: "my_devices" };
    /** @deprecated Use `myImpact` instead. This alias will be removed in the next major version. */
    readonly "my_impact": Omit<typeof tablesSchema.schemaType.tables["myImpact"], "accessorName"> & { readonly accessorName: "my_impact" };
    /** @deprecated Use `myLocation` instead. This alias will be removed in the next major version. */
    readonly "my_location": Omit<typeof tablesSchema.schemaType.tables["myLocation"], "accessorName"> & { readonly accessorName: "my_location" };
    /** @deprecated Use `myPosts` instead. This alias will be removed in the next major version. */
    readonly "my_posts": Omit<typeof tablesSchema.schemaType.tables["myPosts"], "accessorName"> & { readonly accessorName: "my_posts" };
    /** @deprecated Use `myProfile` instead. This alias will be removed in the next major version. */
    readonly "my_profile": Omit<typeof tablesSchema.schemaType.tables["myProfile"], "accessorName"> & { readonly accessorName: "my_profile" };
    /** @deprecated Use `myPrompts` instead. This alias will be removed in the next major version. */
    readonly "my_prompts": Omit<typeof tablesSchema.schemaType.tables["myPrompts"], "accessorName"> & { readonly accessorName: "my_prompts" };
    /** @deprecated Use `myQueries` instead. This alias will be removed in the next major version. */
    readonly "my_queries": Omit<typeof tablesSchema.schemaType.tables["myQueries"], "accessorName"> & { readonly accessorName: "my_queries" };
    /** @deprecated Use `myQueryEvents` instead. This alias will be removed in the next major version. */
    readonly "my_query_events": Omit<typeof tablesSchema.schemaType.tables["myQueryEvents"], "accessorName"> & { readonly accessorName: "my_query_events" };
    /** @deprecated Use `pulseComments` instead. This alias will be removed in the next major version. */
    readonly "pulse_comments": Omit<typeof tablesSchema.schemaType.tables["pulseComments"], "accessorName"> & { readonly accessorName: "pulse_comments" };
    /** @deprecated Use `pulsePosts` instead. This alias will be removed in the next major version. */
    readonly "pulse_posts": Omit<typeof tablesSchema.schemaType.tables["pulsePosts"], "accessorName"> & { readonly accessorName: "pulse_posts" };
    /** @deprecated Use `svcComment` instead. This alias will be removed in the next major version. */
    readonly "svc_comment": Omit<typeof tablesSchema.schemaType.tables["svcComment"], "accessorName"> & { readonly accessorName: "svc_comment" };
    /** @deprecated Use `svcDevice` instead. This alias will be removed in the next major version. */
    readonly "svc_device": Omit<typeof tablesSchema.schemaType.tables["svcDevice"], "accessorName"> & { readonly accessorName: "svc_device" };
    /** @deprecated Use `svcEvidenceJob` instead. This alias will be removed in the next major version. */
    readonly "svc_evidence_job": Omit<typeof tablesSchema.schemaType.tables["svcEvidenceJob"], "accessorName"> & { readonly accessorName: "svc_evidence_job" };
    /** @deprecated Use `svcImpactEvent` instead. This alias will be removed in the next major version. */
    readonly "svc_impact_event": Omit<typeof tablesSchema.schemaType.tables["svcImpactEvent"], "accessorName"> & { readonly accessorName: "svc_impact_event" };
    /** @deprecated Use `svcObservation` instead. This alias will be removed in the next major version. */
    readonly "svc_observation": Omit<typeof tablesSchema.schemaType.tables["svcObservation"], "accessorName"> & { readonly accessorName: "svc_observation" };
    /** @deprecated Use `svcPost` instead. This alias will be removed in the next major version. */
    readonly "svc_post": Omit<typeof tablesSchema.schemaType.tables["svcPost"], "accessorName"> & { readonly accessorName: "svc_post" };
    /** @deprecated Use `svcPromptBatch` instead. This alias will be removed in the next major version. */
    readonly "svc_prompt_batch": Omit<typeof tablesSchema.schemaType.tables["svcPromptBatch"], "accessorName"> & { readonly accessorName: "svc_prompt_batch" };
    /** @deprecated Use `svcPromptRecipient` instead. This alias will be removed in the next major version. */
    readonly "svc_prompt_recipient": Omit<typeof tablesSchema.schemaType.tables["svcPromptRecipient"], "accessorName"> & { readonly accessorName: "svc_prompt_recipient" };
    /** @deprecated Use `svcPromptResponse` instead. This alias will be removed in the next major version. */
    readonly "svc_prompt_response": Omit<typeof tablesSchema.schemaType.tables["svcPromptResponse"], "accessorName"> & { readonly accessorName: "svc_prompt_response" };
    /** @deprecated Use `svcQuery` instead. This alias will be removed in the next major version. */
    readonly "svc_query": Omit<typeof tablesSchema.schemaType.tables["svcQuery"], "accessorName"> & { readonly accessorName: "svc_query" };
    /** @deprecated Use `svcQueryEvent` instead. This alias will be removed in the next major version. */
    readonly "svc_query_event": Omit<typeof tablesSchema.schemaType.tables["svcQueryEvent"], "accessorName"> & { readonly accessorName: "svc_query_event" };
    /** @deprecated Use `svcReport` instead. This alias will be removed in the next major version. */
    readonly "svc_report": Omit<typeof tablesSchema.schemaType.tables["svcReport"], "accessorName"> & { readonly accessorName: "svc_report" };
    /** @deprecated Use `svcUserLocation` instead. This alias will be removed in the next major version. */
    readonly "svc_user_location": Omit<typeof tablesSchema.schemaType.tables["svcUserLocation"], "accessorName"> & { readonly accessorName: "svc_user_location" };
    /** @deprecated Use `svcUserProfile` instead. This alias will be removed in the next major version. */
    readonly "svc_user_profile": Omit<typeof tablesSchema.schemaType.tables["svcUserProfile"], "accessorName"> & { readonly accessorName: "svc_user_profile" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "my_comments": "myComments",
  "my_devices": "myDevices",
  "my_impact": "myImpact",
  "my_location": "myLocation",
  "my_posts": "myPosts",
  "my_profile": "myProfile",
  "my_prompts": "myPrompts",
  "my_queries": "myQueries",
  "my_query_events": "myQueryEvents",
  "pulse_comments": "pulseComments",
  "pulse_posts": "pulsePosts",
  "svc_comment": "svcComment",
  "svc_device": "svcDevice",
  "svc_evidence_job": "svcEvidenceJob",
  "svc_impact_event": "svcImpactEvent",
  "svc_observation": "svcObservation",
  "svc_post": "svcPost",
  "svc_prompt_batch": "svcPromptBatch",
  "svc_prompt_recipient": "svcPromptRecipient",
  "svc_prompt_response": "svcPromptResponse",
  "svc_query": "svcQuery",
  "svc_query_event": "svcQueryEvent",
  "svc_report": "svcReport",
  "svc_user_location": "svcUserLocation",
  "svc_user_profile": "svcUserProfile",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `myComments` instead. This alias will be removed in the next major version. */
  readonly "my_comments": __DbViewBase["myComments"];
  /** @deprecated Use `myDevices` instead. This alias will be removed in the next major version. */
  readonly "my_devices": __DbViewBase["myDevices"];
  /** @deprecated Use `myImpact` instead. This alias will be removed in the next major version. */
  readonly "my_impact": __DbViewBase["myImpact"];
  /** @deprecated Use `myLocation` instead. This alias will be removed in the next major version. */
  readonly "my_location": __DbViewBase["myLocation"];
  /** @deprecated Use `myPosts` instead. This alias will be removed in the next major version. */
  readonly "my_posts": __DbViewBase["myPosts"];
  /** @deprecated Use `myProfile` instead. This alias will be removed in the next major version. */
  readonly "my_profile": __DbViewBase["myProfile"];
  /** @deprecated Use `myPrompts` instead. This alias will be removed in the next major version. */
  readonly "my_prompts": __DbViewBase["myPrompts"];
  /** @deprecated Use `myQueries` instead. This alias will be removed in the next major version. */
  readonly "my_queries": __DbViewBase["myQueries"];
  /** @deprecated Use `myQueryEvents` instead. This alias will be removed in the next major version. */
  readonly "my_query_events": __DbViewBase["myQueryEvents"];
  /** @deprecated Use `pulseComments` instead. This alias will be removed in the next major version. */
  readonly "pulse_comments": __DbViewBase["pulseComments"];
  /** @deprecated Use `pulsePosts` instead. This alias will be removed in the next major version. */
  readonly "pulse_posts": __DbViewBase["pulsePosts"];
  /** @deprecated Use `svcComment` instead. This alias will be removed in the next major version. */
  readonly "svc_comment": __DbViewBase["svcComment"];
  /** @deprecated Use `svcDevice` instead. This alias will be removed in the next major version. */
  readonly "svc_device": __DbViewBase["svcDevice"];
  /** @deprecated Use `svcEvidenceJob` instead. This alias will be removed in the next major version. */
  readonly "svc_evidence_job": __DbViewBase["svcEvidenceJob"];
  /** @deprecated Use `svcImpactEvent` instead. This alias will be removed in the next major version. */
  readonly "svc_impact_event": __DbViewBase["svcImpactEvent"];
  /** @deprecated Use `svcObservation` instead. This alias will be removed in the next major version. */
  readonly "svc_observation": __DbViewBase["svcObservation"];
  /** @deprecated Use `svcPost` instead. This alias will be removed in the next major version. */
  readonly "svc_post": __DbViewBase["svcPost"];
  /** @deprecated Use `svcPromptBatch` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_batch": __DbViewBase["svcPromptBatch"];
  /** @deprecated Use `svcPromptRecipient` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_recipient": __DbViewBase["svcPromptRecipient"];
  /** @deprecated Use `svcPromptResponse` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_response": __DbViewBase["svcPromptResponse"];
  /** @deprecated Use `svcQuery` instead. This alias will be removed in the next major version. */
  readonly "svc_query": __DbViewBase["svcQuery"];
  /** @deprecated Use `svcQueryEvent` instead. This alias will be removed in the next major version. */
  readonly "svc_query_event": __DbViewBase["svcQueryEvent"];
  /** @deprecated Use `svcReport` instead. This alias will be removed in the next major version. */
  readonly "svc_report": __DbViewBase["svcReport"];
  /** @deprecated Use `svcUserLocation` instead. This alias will be removed in the next major version. */
  readonly "svc_user_location": __DbViewBase["svcUserLocation"];
  /** @deprecated Use `svcUserProfile` instead. This alias will be removed in the next major version. */
  readonly "svc_user_profile": __DbViewBase["svcUserProfile"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `myComments` instead. This alias will be removed in the next major version. */
  readonly "my_comments": __TablesBase["myComments"];
  /** @deprecated Use `myDevices` instead. This alias will be removed in the next major version. */
  readonly "my_devices": __TablesBase["myDevices"];
  /** @deprecated Use `myImpact` instead. This alias will be removed in the next major version. */
  readonly "my_impact": __TablesBase["myImpact"];
  /** @deprecated Use `myLocation` instead. This alias will be removed in the next major version. */
  readonly "my_location": __TablesBase["myLocation"];
  /** @deprecated Use `myPosts` instead. This alias will be removed in the next major version. */
  readonly "my_posts": __TablesBase["myPosts"];
  /** @deprecated Use `myProfile` instead. This alias will be removed in the next major version. */
  readonly "my_profile": __TablesBase["myProfile"];
  /** @deprecated Use `myPrompts` instead. This alias will be removed in the next major version. */
  readonly "my_prompts": __TablesBase["myPrompts"];
  /** @deprecated Use `myQueries` instead. This alias will be removed in the next major version. */
  readonly "my_queries": __TablesBase["myQueries"];
  /** @deprecated Use `myQueryEvents` instead. This alias will be removed in the next major version. */
  readonly "my_query_events": __TablesBase["myQueryEvents"];
  /** @deprecated Use `pulseComments` instead. This alias will be removed in the next major version. */
  readonly "pulse_comments": __TablesBase["pulseComments"];
  /** @deprecated Use `pulsePosts` instead. This alias will be removed in the next major version. */
  readonly "pulse_posts": __TablesBase["pulsePosts"];
  /** @deprecated Use `svcComment` instead. This alias will be removed in the next major version. */
  readonly "svc_comment": __TablesBase["svcComment"];
  /** @deprecated Use `svcDevice` instead. This alias will be removed in the next major version. */
  readonly "svc_device": __TablesBase["svcDevice"];
  /** @deprecated Use `svcEvidenceJob` instead. This alias will be removed in the next major version. */
  readonly "svc_evidence_job": __TablesBase["svcEvidenceJob"];
  /** @deprecated Use `svcImpactEvent` instead. This alias will be removed in the next major version. */
  readonly "svc_impact_event": __TablesBase["svcImpactEvent"];
  /** @deprecated Use `svcObservation` instead. This alias will be removed in the next major version. */
  readonly "svc_observation": __TablesBase["svcObservation"];
  /** @deprecated Use `svcPost` instead. This alias will be removed in the next major version. */
  readonly "svc_post": __TablesBase["svcPost"];
  /** @deprecated Use `svcPromptBatch` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_batch": __TablesBase["svcPromptBatch"];
  /** @deprecated Use `svcPromptRecipient` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_recipient": __TablesBase["svcPromptRecipient"];
  /** @deprecated Use `svcPromptResponse` instead. This alias will be removed in the next major version. */
  readonly "svc_prompt_response": __TablesBase["svcPromptResponse"];
  /** @deprecated Use `svcQuery` instead. This alias will be removed in the next major version. */
  readonly "svc_query": __TablesBase["svcQuery"];
  /** @deprecated Use `svcQueryEvent` instead. This alias will be removed in the next major version. */
  readonly "svc_query_event": __TablesBase["svcQueryEvent"];
  /** @deprecated Use `svcReport` instead. This alias will be removed in the next major version. */
  readonly "svc_report": __TablesBase["svcReport"];
  /** @deprecated Use `svcUserLocation` instead. This alias will be removed in the next major version. */
  readonly "svc_user_location": __TablesBase["svcUserLocation"];
  /** @deprecated Use `svcUserProfile` instead. This alias will be removed in the next major version. */
  readonly "svc_user_profile": __TablesBase["svcUserProfile"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

