// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  batchId: __t.u64().primaryKey().name("batch_id"),
  recipientId: __t.u64().name("recipient_id"),
  placeId: __t.string().name("place_id"),
  placeName: __t.string().name("place_name"),
  placeCategory: __t.string().name("place_category"),
  placeAddress: __t.string().name("place_address"),
  question: __t.string(),
  controlsJson: __t.string().name("controls_json"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  notifiedAt: __t.option(__t.timestamp()).name("notified_at"),
  responded: __t.bool(),
});
