// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  postId: __t.u64().name("post_id"),
  attribution: __t.string(),
  authorLabel: __t.string().name("author_label"),
  authorAvatarSeed: __t.option(__t.string()).name("author_avatar_seed"),
  text: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
