// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  attribution: __t.string(),
  authorLabel: __t.string().name("author_label"),
  authorAvatarSeed: __t.option(__t.string()).name("author_avatar_seed"),
  placeId: __t.string().name("place_id"),
  community: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  summary: __t.string(),
  freshnessState: __t.string().name("freshness_state"),
  freshnessNote: __t.string().name("freshness_note"),
  commentCount: __t.u32().name("comment_count"),
  claimsJson: __t.option(__t.string()).name("claims_json"),
});
