// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string().name("p_256_dh"),
  auth: __t.string(),
  userAgent: __t.string().name("user_agent"),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  svc: __t.u8(),
});
