// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  batchId: __t.u64().name("batch_id"),
  jobId: __t.u64().name("job_id"),
  responder: __t.identity(),
  notifiedAt: __t.option(__t.timestamp()).name("notified_at"),
  responded: __t.bool(),
  svc: __t.u8(),
});
