// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  reporter: __t.identity(),
  targetType: __t.string().name("target_type"),
  targetId: __t.u64().name("target_id"),
  reason: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  dedupKey: __t.string().name("dedup_key"),
  svc: __t.u8(),
});
