// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  clientKey: __t.string().name("client_key"),
  placeId: __t.string().name("place_id"),
  intentKey: __t.string().name("intent_key"),
  dimensionKeysJson: __t.string().name("dimension_keys_json"),
  status: __t.string(),
  planJson: __t.string().name("plan_json"),
  createdAt: __t.timestamp().name("created_at"),
  deadlineAt: __t.timestamp().name("deadline_at"),
  recipientsCount: __t.u32().name("recipients_count"),
  confidenceJson: __t.option(__t.string()).name("confidence_json"),
  svc: __t.u8(),
});
