// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  batchId: __t.u64().name("batch_id"),
  responder: __t.identity(),
  answersJson: __t.string().name("answers_json"),
  note: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  respKey: __t.string().name("resp_key"),
  svc: __t.u8(),
});
