// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  placeId: __t.string().name("place_id"),
  dimension: __t.string(),
  value: __t.string(),
  valueLabel: __t.string().name("value_label"),
  ordinal: __t.option(__t.i32()),
  kind: __t.string(),
  sourceType: __t.string().name("source_type"),
  sourceId: __t.string().name("source_id"),
  contributor: __t.option(__t.identity()),
  verifiedNearby: __t.bool().name("verified_nearby"),
  observedAt: __t.timestamp().name("observed_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  invalidated: __t.bool(),
  dedupKey: __t.string().name("dedup_key"),
  svc: __t.u8(),
});
