// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  requester: __t.identity(),
  placeId: __t.string().name("place_id"),
  text: __t.string(),
  status: __t.string(),
  evidenceJobId: __t.option(__t.u64()).name("evidence_job_id"),
  planJson: __t.option(__t.string()).name("plan_json"),
  clarificationJson: __t.option(__t.string()).name("clarification_json"),
  clarificationChoice: __t.option(__t.string()).name("clarification_choice"),
  answerJson: __t.option(__t.string()).name("answer_json"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  clientRequestId: __t.string().name("client_request_id"),
  idemKey: __t.string().name("idem_key"),
  svc: __t.u8(),
});
