// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  queryId: __t.u64().name("query_id"),
  owner: __t.identity(),
  title: __t.string(),
  body: __t.string(),
  url: __t.string(),
  tag: __t.string(),
  state: __t.string(),
  attempts: __t.u16(),
  nextAttemptAt: __t.timestamp().name("next_attempt_at"),
  createdAt: __t.timestamp().name("created_at"),
  svc: __t.u8(),
});
