// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  owner: __t.identity(),
  placeId: __t.string().name("place_id"),
  text: __t.string(),
  idemKey: __t.string().name("idem_key"),
  dimensionKeysJson: __t.string().name("dimension_keys_json"),
  targetJson: __t.string().name("target_json"),
  status: __t.string(),
  lastValue: __t.string().name("last_value"),
  lastNotifiedAt: __t.option(__t.timestamp()).name("last_notified_at"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAt: __t.timestamp().name("expires_at"),
  svc: __t.u8(),
});
