// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AnswerNotification = __t.object("AnswerNotification", {
  key: __t.string(),
  queryId: __t.u64(),
  owner: __t.identity(),
  title: __t.string(),
  body: __t.string(),
  url: __t.string(),
  tag: __t.string(),
  state: __t.string(),
  attempts: __t.u16(),
  nextAttemptAt: __t.timestamp(),
  createdAt: __t.timestamp(),
  svc: __t.u8(),
});
export type AnswerNotification = __Infer<typeof AnswerNotification>;

export const Comment = __t.object("Comment", {
  id: __t.u64(),
  postId: __t.u64(),
  author: __t.identity(),
  attribution: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  deleted: __t.bool(),
  hidden: __t.bool(),
  svc: __t.u8(),
});
export type Comment = __Infer<typeof Comment>;

export const DemoName = __t.object("DemoName", {
  identity: __t.identity(),
  displayName: __t.string(),
});
export type DemoName = __Infer<typeof DemoName>;

export const Device = __t.object("Device", {
  id: __t.u64(),
  owner: __t.identity(),
  endpoint: __t.string(),
  p256Dh: __t.string(),
  auth: __t.string(),
  userAgent: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  svc: __t.u8(),
});
export type Device = __Infer<typeof Device>;

export const EvidenceJob = __t.object("EvidenceJob", {
  id: __t.u64(),
  clientKey: __t.string(),
  placeId: __t.string(),
  intentKey: __t.string(),
  dimensionKeysJson: __t.string(),
  status: __t.string(),
  planJson: __t.string(),
  createdAt: __t.timestamp(),
  deadlineAt: __t.timestamp(),
  recipientsCount: __t.u32(),
  confidenceJson: __t.option(__t.string()),
  svc: __t.u8(),
  deadlinePassed: __t.bool(),
});
export type EvidenceJob = __Infer<typeof EvidenceJob>;

export const GcSchedule = __t.object("GcSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GcSchedule = __Infer<typeof GcSchedule>;

export const ImpactEvent = __t.object("ImpactEvent", {
  id: __t.u64(),
  contributor: __t.identity(),
  sourceType: __t.string(),
  sourceId: __t.string(),
  queryId: __t.u64(),
  kind: __t.string(),
  createdAt: __t.timestamp(),
  dedupKey: __t.string(),
  svc: __t.u8(),
});
export type ImpactEvent = __Infer<typeof ImpactEvent>;

export const JobDeadlineSchedule = __t.object("JobDeadlineSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  jobId: __t.u64(),
});
export type JobDeadlineSchedule = __Infer<typeof JobDeadlineSchedule>;

export const ModuleOwner = __t.object("ModuleOwner", {
  id: __t.u8(),
  identity: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const MyCommentId = __t.object("MyCommentId", {
  commentId: __t.u64(),
});
export type MyCommentId = __Infer<typeof MyCommentId>;

export const MyComments = __t.object("MyComments", {});
export type MyComments = __Infer<typeof MyComments>;

export const MyDevices = __t.object("MyDevices", {});
export type MyDevices = __Infer<typeof MyDevices>;

export const MyImpact = __t.object("MyImpact", {});
export type MyImpact = __Infer<typeof MyImpact>;

export const MyLocation = __t.object("MyLocation", {});
export type MyLocation = __Infer<typeof MyLocation>;

export const MyPostId = __t.object("MyPostId", {
  postId: __t.u64(),
});
export type MyPostId = __Infer<typeof MyPostId>;

export const MyPosts = __t.object("MyPosts", {});
export type MyPosts = __Infer<typeof MyPosts>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const MyPrompts = __t.object("MyPrompts", {});
export type MyPrompts = __Infer<typeof MyPrompts>;

export const MyQueries = __t.object("MyQueries", {});
export type MyQueries = __Infer<typeof MyQueries>;

export const MyQueryEvents = __t.object("MyQueryEvents", {});
export type MyQueryEvents = __Infer<typeof MyQueryEvents>;

export const MyWatches = __t.object("MyWatches", {});
export type MyWatches = __Infer<typeof MyWatches>;

export const Observation = __t.object("Observation", {
  id: __t.u64(),
  placeId: __t.string(),
  dimension: __t.string(),
  value: __t.string(),
  valueLabel: __t.string(),
  ordinal: __t.option(__t.i32()),
  kind: __t.string(),
  sourceType: __t.string(),
  sourceId: __t.string(),
  contributor: __t.option(__t.identity()),
  verifiedNearby: __t.bool(),
  observedAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  invalidated: __t.bool(),
  dedupKey: __t.string(),
  svc: __t.u8(),
});
export type Observation = __Infer<typeof Observation>;

export const Place = __t.object("Place", {
  id: __t.string(),
  name: __t.string(),
  category: __t.string(),
  lat: __t.f64(),
  lng: __t.f64(),
  address: __t.string(),
  community: __t.string(),
});
export type Place = __Infer<typeof Place>;

export const Post = __t.object("Post", {
  id: __t.u64(),
  author: __t.identity(),
  attribution: __t.string(),
  placeId: __t.string(),
  community: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  deleted: __t.bool(),
  hidden: __t.bool(),
  summary: __t.string(),
  freshnessState: __t.string(),
  freshnessNote: __t.string(),
  commentCount: __t.u32(),
  claimsJson: __t.option(__t.string()),
  svc: __t.u8(),
});
export type Post = __Infer<typeof Post>;

export const PromptBatch = __t.object("PromptBatch", {
  id: __t.u64(),
  jobId: __t.u64(),
  placeId: __t.string(),
  question: __t.string(),
  controlsJson: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  svc: __t.u8(),
  expired: __t.bool(),
});
export type PromptBatch = __Infer<typeof PromptBatch>;

export const PromptExpirySchedule = __t.object("PromptExpirySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  batchId: __t.u64(),
});
export type PromptExpirySchedule = __Infer<typeof PromptExpirySchedule>;

export const PromptForMe = __t.object("PromptForMe", {
  batchId: __t.u64(),
  recipientId: __t.u64(),
  placeId: __t.string(),
  placeName: __t.string(),
  placeCategory: __t.string(),
  placeAddress: __t.string(),
  question: __t.string(),
  controlsJson: __t.string(),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  notifiedAt: __t.option(__t.timestamp()),
  responded: __t.bool(),
  expired: __t.bool(),
});
export type PromptForMe = __Infer<typeof PromptForMe>;

export const PromptRecipient = __t.object("PromptRecipient", {
  id: __t.u64(),
  batchId: __t.u64(),
  jobId: __t.u64(),
  responder: __t.identity(),
  notifiedAt: __t.option(__t.timestamp()),
  responded: __t.bool(),
  svc: __t.u8(),
});
export type PromptRecipient = __Infer<typeof PromptRecipient>;

export const PromptResponse = __t.object("PromptResponse", {
  id: __t.u64(),
  batchId: __t.u64(),
  responder: __t.identity(),
  answersJson: __t.string(),
  note: __t.string(),
  createdAt: __t.timestamp(),
  respKey: __t.string(),
  svc: __t.u8(),
});
export type PromptResponse = __Infer<typeof PromptResponse>;

export const PulseComment = __t.object("PulseComment", {
  id: __t.u64(),
  postId: __t.u64(),
  attribution: __t.string(),
  authorLabel: __t.string(),
  authorAvatarSeed: __t.option(__t.string()),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type PulseComment = __Infer<typeof PulseComment>;

export const PulseComments = __t.object("PulseComments", {});
export type PulseComments = __Infer<typeof PulseComments>;

export const PulsePost = __t.object("PulsePost", {
  id: __t.u64(),
  attribution: __t.string(),
  authorLabel: __t.string(),
  authorAvatarSeed: __t.option(__t.string()),
  placeId: __t.string(),
  community: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
  summary: __t.string(),
  freshnessState: __t.string(),
  freshnessNote: __t.string(),
  commentCount: __t.u32(),
  claimsJson: __t.option(__t.string()),
  verifiedNearby: __t.bool(),
});
export type PulsePost = __Infer<typeof PulsePost>;

export const PulsePosts = __t.object("PulsePosts", {});
export type PulsePosts = __Infer<typeof PulsePosts>;

export const Query = __t.object("Query", {
  id: __t.u64(),
  requester: __t.identity(),
  placeId: __t.string(),
  text: __t.string(),
  status: __t.string(),
  evidenceJobId: __t.option(__t.u64()),
  planJson: __t.option(__t.string()),
  clarificationJson: __t.option(__t.string()),
  clarificationChoice: __t.option(__t.string()),
  answerJson: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  clientRequestId: __t.string(),
  idemKey: __t.string(),
  svc: __t.u8(),
});
export type Query = __Infer<typeof Query>;

export const QueryEvent = __t.object("QueryEvent", {
  id: __t.u64(),
  queryId: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
  svc: __t.u8(),
});
export type QueryEvent = __Infer<typeof QueryEvent>;

export const RateBucket = __t.object("RateBucket", {
  key: __t.string(),
  count: __t.u32(),
});
export type RateBucket = __Infer<typeof RateBucket>;

export const Report = __t.object("Report", {
  id: __t.u64(),
  reporter: __t.identity(),
  targetType: __t.string(),
  targetId: __t.u64(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
  dedupKey: __t.string(),
  svc: __t.u8(),
});
export type Report = __Infer<typeof Report>;

export const ServiceRole = __t.object("ServiceRole", {
  identity: __t.identity(),
  createdAt: __t.timestamp(),
  svc: __t.u8(),
});
export type ServiceRole = __Infer<typeof ServiceRole>;

export const SvcAnswerNotification = __t.object("SvcAnswerNotification", {});
export type SvcAnswerNotification = __Infer<typeof SvcAnswerNotification>;

export const SvcComment = __t.object("SvcComment", {});
export type SvcComment = __Infer<typeof SvcComment>;

export const SvcDevice = __t.object("SvcDevice", {});
export type SvcDevice = __Infer<typeof SvcDevice>;

export const SvcEvidenceJob = __t.object("SvcEvidenceJob", {});
export type SvcEvidenceJob = __Infer<typeof SvcEvidenceJob>;

export const SvcImpactEvent = __t.object("SvcImpactEvent", {});
export type SvcImpactEvent = __Infer<typeof SvcImpactEvent>;

export const SvcObservation = __t.object("SvcObservation", {});
export type SvcObservation = __Infer<typeof SvcObservation>;

export const SvcPost = __t.object("SvcPost", {});
export type SvcPost = __Infer<typeof SvcPost>;

export const SvcPromptBatch = __t.object("SvcPromptBatch", {});
export type SvcPromptBatch = __Infer<typeof SvcPromptBatch>;

export const SvcPromptRecipient = __t.object("SvcPromptRecipient", {});
export type SvcPromptRecipient = __Infer<typeof SvcPromptRecipient>;

export const SvcPromptResponse = __t.object("SvcPromptResponse", {});
export type SvcPromptResponse = __Infer<typeof SvcPromptResponse>;

export const SvcQuery = __t.object("SvcQuery", {});
export type SvcQuery = __Infer<typeof SvcQuery>;

export const SvcQueryEvent = __t.object("SvcQueryEvent", {});
export type SvcQueryEvent = __Infer<typeof SvcQueryEvent>;

export const SvcReport = __t.object("SvcReport", {});
export type SvcReport = __Infer<typeof SvcReport>;

export const SvcUserLocation = __t.object("SvcUserLocation", {});
export type SvcUserLocation = __Infer<typeof SvcUserLocation>;

export const SvcUserPresence = __t.object("SvcUserPresence", {});
export type SvcUserPresence = __Infer<typeof SvcUserPresence>;

export const SvcUserProfile = __t.object("SvcUserProfile", {});
export type SvcUserProfile = __Infer<typeof SvcUserProfile>;

export const SvcWatch = __t.object("SvcWatch", {});
export type SvcWatch = __Infer<typeof SvcWatch>;

export const UserLocation = __t.object("UserLocation", {
  identity: __t.identity(),
  lat: __t.f64(),
  lng: __t.f64(),
  accuracyM: __t.f64(),
  source: __t.string(),
  claimedPlaceId: __t.option(__t.string()),
  capturedAt: __t.timestamp(),
  svc: __t.u8(),
});
export type UserLocation = __Infer<typeof UserLocation>;

export const UserPresence = __t.object("UserPresence", {
  connectionId: __t.string(),
  identity: __t.identity(),
  lastSeenAt: __t.timestamp(),
  svc: __t.u8(),
});
export type UserPresence = __Infer<typeof UserPresence>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  username: __t.string(),
  avatarSeed: __t.string(),
  defaultAttribution: __t.string(),
  notificationsPaused: __t.bool(),
  isAdmin: __t.bool(),
  createdAt: __t.timestamp(),
  svc: __t.u8(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const Watch = __t.object("Watch", {
  id: __t.u64(),
  owner: __t.identity(),
  placeId: __t.string(),
  text: __t.string(),
  idemKey: __t.string(),
  dimensionKeysJson: __t.string(),
  targetJson: __t.string(),
  status: __t.string(),
  lastValue: __t.string(),
  lastNotifiedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  expiresAt: __t.timestamp(),
  svc: __t.u8(),
});
export type Watch = __Infer<typeof Watch>;

export const WatchExpirySchedule = __t.object("WatchExpirySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  watchId: __t.u64(),
});
export type WatchExpirySchedule = __Infer<typeof WatchExpirySchedule>;

