// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  placeId: __t.string(),
  dimension: __t.string(),
  value: __t.string(),
  valueLabel: __t.string(),
  ordinal: __t.option(__t.i32()),
  kind: __t.string(),
  sourceType: __t.string(),
  sourceId: __t.string(),
  contributor: __t.option(__t.identity()),
  verifiedNearby: __t.bool(),
  observedAtMicros: __t.u64(),
  expiresAtMicros: __t.u64(),
};
