// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  clientKey: __t.string(),
  placeId: __t.string(),
  intentKey: __t.string(),
  dimensionKeysJson: __t.string(),
  planJson: __t.string(),
  deadlineAtMicros: __t.u64(),
};
